name: test-expiration-ci

on:
  pull_request:
    paths:
      - 'expiration/**'

jobs:
  build:
    # Execute the workflow on ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install specifiv node version
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Execute Expiration Microservice test cases
      - name: Run Expiration Microservice Tests
        run: |
          cd expiration
          yarn install
          yarn test:ci