name: test-payments-ci

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    # Execute the workflow on ubuntu
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install specifiv node version
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Execute Payments Microservice test cases
      - name: Run payments Microservice Tests
        run: |
          cd payments
          yarn install
          yarn test:ci